pipeline {
    agent any    
	stages {
	    stage('GIT Checkout') {
	    	steps{
	        	 git branch: 'master',
	    		credentialsId: 'a1aa10b3-85ab-4296-a59a-5d6f78604ea2',
	    		url: 'https://github.com/saurabhwaikar/mvn-module-jenkinsfile.git'
	    	}   	  
    	}
    	
    	stage('MVN Build'){
			steps {
				sh 'mvn -f parentproj/pom.xml package'    // As pom.xml in inside parent project need to give full path
			}
    	}

		stage('Deploy to Tomcat'){
			steps {
				deploy adapters: [tomcat8(credentialsId: 'tomcat-deployer', path: '', 
								url: 'http://localhost:8121')], 
						contextPath: '/modulone', 
						war : '**/*.war'
						//war: '/var/lib/jenkins/workspace/maven-module-jenkinsfile/parentproj/childmoduleone/target/childmoduleone-0.0.1-SNAPSHOT.war'
			}
    	}
	}
	
}
